# Generated by Django 4.2.3 on 2024-08-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_commentdislikes_commentlikes_postdislikes_postlikes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentdislikes',
            options={'verbose_name': 'Comment dislike', 'verbose_name_plural': 'Comment dislikes'},
        ),
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'verbose_name': 'Comment like', 'verbose_name_plural': 'Comment likes'},
        ),
        migrations.AlterModelOptions(
            name='postdislikes',
            options={'verbose_name': 'Post dislike', 'verbose_name_plural': 'Post dislikes'},
        ),
        migrations.AlterModelOptions(
            name='postlikes',
            options={'verbose_name': 'Post like', 'verbose_name_plural': 'Post likes'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='replydislikes',
            options={'verbose_name': 'Reply dislike', 'verbose_name_plural': 'Reply dislikes'},
        ),
        migrations.AlterModelOptions(
            name='replylikes',
            options={'verbose_name': 'Reply like', 'verbose_name_plural': 'Reply likes'},
        ),
    ]
