# Generated by Django 4.2.3 on 2024-08-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_today_deal',
            field=models.BooleanField(default=False),
        ),
    ]
